name: nginx-mutual-tls

services:
  nginx:
    image: nginx:latest
    restart: no
    ports:
      - target: 80
        # published: ${NGINX_HTTP:-8098}
      - target: 443
        published: ${NGINX_HTTPS:-8448}
    environment:
      conf: /etc/nginx/conf.d
      in_docker: true
    volumes:
      - "./conf:/etc/nginx/conf.d"
      - source: ./configure.sh
        target: /configure.sh
        type: bind
      - "./test.sh:/test.sh"
