name: nginx-mutual-tls

services:
  nginx:
    image: nginx:latest
    restart: no
    ports:
      - target: 80
        #published: ${NGINX_HTTP:-8098}
      - target: 443
        published: ${NGINX_HTTPS:-8448}
    volumes:
      - "./conf:/etc/nginx/conf.d:ro"
